Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/rec_svtr_tiny_digital/
  save_epoch_step: 3
  eval_batch_step:
  - 0
  - 500
  cal_metric_during_train: true
  pretrained_model: rec_svtr_tiny_none_ctc_ch_train/best_accuracy
  checkpoints: null
  save_inference_dir: digital_infer
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ./digital_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  save_res_path: ./output/rec/predicts_svtr_tiny_ch.txt
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 8.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 1.0e-05
    warmup_epoch: 5
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize:
    - 32
    - 64
    tps_outputsize:
    - 32
    - 320
    num_control_points: 20
    tps_margins:
    - 0.05
    - 0.05
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size:
    - 32
    - 320
    out_char_num: 40
    out_channels: 192
    patch_merging: Conv
    embed_dim:
    - 64
    - 128
    - 256
    depth:
    - 3
    - 6
    - 3
    num_heads:
    - 2
    - 4
    - 8
    mixer:
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/digital_img_fl
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/digital_img_fl/digital_train.txt
    - ./train_data/digital_img_fl/real_train.txt
    - ./train_data/digital_img_fl/pubtabnet_crop_new.txt
    - ./train_data/digital_img_fl/dbm_img/dbm.txt
    ratio_list:
    - 0.3
    - 1.0
    - 0.1
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/digital_img_fl/
    label_file_list:
    - ./train_data/digital_img_fl/real_val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 2
profiler_options: null
